language: bash
services: docker

env:
  - VERSION=7.0
  - VERSION=7.1
  - VERSION=7.2
  - VERSION=7.3

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd ${VERSION}
  - image="prestashop/prestashop-git:${VERSION}"
  - image="${image//'/'/-}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
